### ISSUE TITLE
Encountered unsupported path command <class 'svg.path.path.Arc'>

### ISSUE THREAD

**Issue by AiGreek** [BlvckBytes/layout_postproc#1]
Hi again,

Like i said on discord, the command seems to be ok, but i have an error as output
![image](https://user-images.githubusercontent.com/16197044/203091511-a8825589-5bf5-48dc-bf7c-0d27997c5b53.png)

Good luck and thanks for this script !

**Comment by BlvckBytes** [comment]
Hey there!

Thank you so much for checking out my script and actually taking the time to test it!

I have now added the Arc path command to the list of supported commands, as it also just has a start- and an end coordinate which can be shifted easily. If you get any other error messages it might help to provide me with your SVG test pattern, as long as that's okay with you.

**Comment by AiGreek** [comment]
well not finished yet 
![image](https://user-images.githubusercontent.com/16197044/203107039-b1bcfb10-cc7b-47eb-aa22-6e9a02ca46e0.png)
here's my file. no problem to share it, it's a test to do my own PCB ^^ 
![DIY_TestPattern-brd](https://user-images.githubusercontent.com/16197044/203107069-f28e2a7f-0a56-4a15-8d79-e1d360d16761.svg)

**Comment by BlvckBytes** [comment]
It does work with the latest commit now, but it seems like there is some other stuff embedded into the SVG as well. I need to check that out. Could you check out your plot dialog in the mean time to make sure there's nothing selected besides the copper layers? Maybe even share a quick screenshot.

[layout_postproc.pdf](https://github.com/BlvckBytes/layout_postproc/files/10058461/layout_postproc.pdf)

**Comment by BlvckBytes** [comment]
I also just noticed how the layout is upside down... Not a big deal, but I'm going to work on that next.

**Comment by AiGreek** [comment]
okey this is what i'm doing : 
Opening my pcb file
![image](https://user-images.githubusercontent.com/16197044/203114267-357e986f-8f36-4d59-924b-f626f7ab4e97.png)

I go to File -> Export -> SVG
![image](https://user-images.githubusercontent.com/16197044/203114399-7da8c2fe-792e-4fa6-b8de-7fa5b67edb2a.png)

So my file is now here 
![image](https://user-images.githubusercontent.com/16197044/203114452-0f5c2c3d-7ed2-44f2-be9b-59c075721154.png)

then i open  my terminal anbd write some random value (just for the test)
![image](https://user-images.githubusercontent.com/16197044/203114662-e72a7578-2f76-45ac-9e1d-3f6a4a99b3b6.png)

So i'm thinking "meh wrong permission, i'm gonna create this "tmp" folder myself in C:\ 
Aaaaand i'm not sure what i'm doing wrong
![image](https://user-images.githubusercontent.com/16197044/203115243-e8c742d0-45bf-4540-bbb3-fc106f7fcf42.png)

**Comment by AiGreek** [comment]
Okey it's working
Still wondering why i have this thing 
![image](https://user-images.githubusercontent.com/16197044/203117176-134973a2-a63b-40e2-91f3-e016e3f76c26.png)
BUT it's working :D
You're awesome

**Comment by BlvckBytes** [comment]
Please get rid of all the technical layers, they have no need to be on the final PCB anyways. You're just trying to etch copper, right?

You're on a windows host, which I have next to no experience with... But you could just go into the python script and change the following code right at the head of the file:

```python
temp_folder = '/tmp' # Path for temporary file storage
```

Change it from `/tmp` to `C:\Users\edoua\Desktop`, that'll be fine for now. I have no idea where windows has it's temp folder. Since you got those nasty backslashes in the path, you'll need to use a raw string.

```python
temp_folder = r'C:\Users\edoua\Desktop' # Path for temporary file storage
```

This will put the temporary svg file on your desktop, you can just delete it afterwards.

**Comment by AiGreek** [comment]
Nice ! thanks 
![image](https://user-images.githubusercontent.com/16197044/203118806-a5a0ad8a-471d-4bff-aa08-66e7b312418d.png)

**Comment by BlvckBytes** [comment]
Still looks like you got some weird page artifacts on there... Did you unselect everything besides the front and back copper layers? Btw, did you pull the latest change? The board should no longer be flipped...

**Comment by AiGreek** [comment]
NOW i have the last version (sorryyy)
![image](https://user-images.githubusercontent.com/16197044/203120013-6579af02-8388-44a8-bfcb-96b2e65c79e6.png)
Here's the command
![image](https://user-images.githubusercontent.com/16197044/203120133-15259aa3-8d96-41b1-8b37-af3431aae708.png)
And the result 
![image](https://user-images.githubusercontent.com/16197044/203120176-444bc33c-b921-4ecc-8d40-ebf4432d1f19.png)

**Comment by AiGreek** [comment]
If i'm writing this 
![image](https://user-images.githubusercontent.com/16197044/203120793-deb3c572-0171-4cc4-aa29-44f2755f6ba9.png)
i have an error but pdf is still generated perfectly (almost)
![image](https://user-images.githubusercontent.com/16197044/203120932-f1716373-da3c-435d-af98-a027ee83c3c2.png)

**Comment by BlvckBytes** [comment]
Awesome, it's now the right way up, just how it's supposed to be. I'm still trying to figure out why these artefacts are right over the layout, effectively rendering it unusable.

Are all technical layers off, did you scroll till the bottom? Otherwise, could you please share your project as a zip file with me real quick? I really want to know why this is happening... I have no way of distinguishing these extra paths in the script, as far as I can tell right now.

**Comment by AiGreek** [comment]
yes, nothing is checked except for F.cu.

And here's the zip file. you'll need the last Kicad Nightly update to open it  :/
[DIY_TestPattern.zip](https://github.com/BlvckBytes/layout_postproc/files/10059092/DIY_TestPattern.zip)

**Comment by BlvckBytes** [comment]
I couldn't reproduce this issue, even with the nightly build. I'm running macos, maybe it's a bug related to the windows compilation. Anyways, I'm happy that you solved it by just removing the sheet itself in the Drawing Sheet Editor from KiCad's main menu.

Are there any other issues you're facing now, or is it working out for you?

**Comment by AiGreek** [comment]
it's working perfectly now. Thank you for your very fast support !
i'm gonna take the time to look the code and see what i can do 

Thanks again and don't hesitate to mention me on discord if you need to try some feature(s) or test(s)
